# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1.1
loader_version=0.18.6
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=0.3.0
maven_group=dev.keesmand
archives_base_name=magnet-command
supported_minecraft_version=26.1.1

# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_api_version=0.145.3+26.1.1
# check this on https://maven.nucleoid.xyz/eu/pb4/player-data-api/
player_data_api=0.10.0+26.1
